#!/bin/bash

echo pid = $$
#interval=$1

interval=${1:-3}
lifetime=${2:-3600}
# default to run 1 hour


let time_stop=`date +"%s"`+lifetime

echo "interval  = $interval"
echo "lifetime  = $lifetime"

while [ 1 ]
do
  echo "infinite +$interval = `date`"
  time=`date +"%s"`
  if [ $time -ge $time_stop ] ; then
    echo "Infinite Timeout!"
    break
  fi

  sleep $interval
done
